services:
  - type: web
    name: telegram-video-audio-bot
    env: docker
    plan: free
    region: frankfurt
    healthCheckPath: /ping
    dockerCommand: "python bot.py"
    envVars:
      - key: 
        sync: false  # vous ajouterez la valeur depuis Render Dashboard
    autoDeploy: true
